return {
	["Bandit"] = {
		Damage = 5,
		MaxHealth = 1150,
		SpawnArea = Vector3.new(-40.7, 3.1, -154.995),
		Amount = 1,
		WalkSpeed = 14,
		FollowRange = 55,
		CombatRange = 4,
		RespawnTime = 6,
		Data = {
			Level = 5,
			Strength = 2,
			Defense = 0,
			Fruit = 0,
			Weapon = 0,
			EquippedWeapon = "",
			FightingStyle = "Combat",
			DemonFruit = "",
			Bounty = 15,
		},
	},
	["Bandit Boss"] = {
		Damage = 15,
		MaxHealth = 350,
		SpawnArea = Vector3.new(33.175, 3.894, -70.164),
		Amount = 0,
		WalkSpeed = 14,
		FollowRange = 55,
		CombatRange = 6,
		RespawnTime = 6,
		Data = {
			Level = 5,
			Strength = 2,
			Defense = 0,
			Fruit = 0,
			Weapon = 0,
			EquippedWeapon = "",
			FightingStyle = "Combat",
			DemonFruit = "",
			Bounty = 500,
		},
	},
}
