return {
	["Level"] = 1,
	["Experience"] = 0,
	["MaxExperience"] = 50,
	["DemonFruit"] = "",
	["FightingStyle"] = "Combat",
	["Race"] = "",
	["Variant"] = "",
	["RaceAccessory"] = 1,
	["Strength"] = 1,
	["Defense"] = 1,
	["Fruit"] = 150,
	["Weapon"] = 1,
	["EquippedWeapon"] = "Bomb",
	["Beli"] = 1500000,
	["StatPoints"] = 50,
	["Mastery"] = {
		["Rubber"] = {Level = 1, Experience = 0, MaxExperience = 50},
		["Combat"] = {Level = 1, Experience = 0, MaxExperience = 50},
		["Bomb"] = {Level = 1, Experience = 0, MaxExperience = 50},
		["Flame"] = {Level = 1, Experience = 0, MaxExperience = 50},
		["Light"] = {Level = 1, Experience = 0, MaxExperience = 50},
		["Pika"] = {Level = 1, Experience = 0, MaxExperience = 50},
		["Gravity"] = {Level = 1, Experience = 0, MaxExperience = 50},
		["BlackLeg"] = {Level = 1, Experience = 0, MaxExperience = 50},
		["OneSwordStyle"] = {Level = 1, Experience = 0, MaxExperience = 50},
	},
	["QuestName"] = "",
	["QuestProgress"] = 0,
	["QuestTarget"] = "",
	["QuestMax"] = 0,
	["Inventory"] = {"Light","Flame","Gravity","Rubber"},
	["Bounty"] = 0,
}